/*
 * edit_method_panel.java
 *
 * Created on 4 novembre 2002, 9.54
 */

package org.af1_0.gui.panel;

import java.util.Iterator;

import org.af1_0.entity.*;
import org.af1_0.gui.command.command;

/**
 *
 * @author  Luca
 */
public class edit_method_panel extends javax.swing.JPanel {
    protected java_method method = null;
    command ok_command = null;
    command cancel_command = null;
    
    /** Creates new form edit_method_panel */
    public edit_method_panel() {
        initComponents();
    }
    
    public void setSuggested(java_method the_method) {
        method = new java_method();
        
        method.setName( the_method.getName() );
        method.setType( the_method.getType() );
        method.setVisibility( the_method.getVisibility() );

        nameField.setText( method.getName() );
        typeField.setText( method.getType() );
        
        String vis = method.getVisibility();
        if (vis.equals("public"))
            publicRadioButton.setSelected(true);
        else if (vis.equals("package"))
            packageRadioButton.setSelected(true);
        else if (vis.equals("protected"))
            protectedRadioButton.setSelected(true);
        else
            privateRadioButton.setSelected(true);
        
        staticCB.setSelected(false);
        finalCB.setSelected(false);
        nativeCB.setSelected(false);
        volatileCB.setSelected(false);
        Iterator it = the_method.getModifierList();
        while(it.hasNext()) {
            String mod = (String) it.next();
            if (mod.equals("static"))
                staticCB.setSelected(true);
            else if (mod.equals("final"))
                finalCB.setSelected(true);
            else if (mod.equals("native"))
                nativeCB.setSelected(true);
            else if (mod.equals("volatile"))
                volatileCB.setSelected(true);
        }
                
    }
    
    public java_method getMethod() {
        return method;
    }

    public void setOkCommand(command ok) {
        ok_command = ok;
    }
    
    public void setCancelCommand(command cancel) {
        cancel_command = cancel;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        publicRadioButton = new javax.swing.JRadioButton();
        privateRadioButton = new javax.swing.JRadioButton();
        protectedRadioButton = new javax.swing.JRadioButton();
        packageRadioButton = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        staticCB = new javax.swing.JCheckBox();
        finalCB = new javax.swing.JCheckBox();
        nativeCB = new javax.swing.JCheckBox();
        volatileCB = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jTextField61 = new javax.swing.JTextField();
        jList11 = new javax.swing.JList();
        jPanel8 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        panel1.add(OKButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        panel1.add(CancelButton);

        add(panel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel3.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Visibility"), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 20, 1, 20))));
        publicRadioButton.setText("public");
        buttonGroup1.add(publicRadioButton);
        jPanel3.add(publicRadioButton);

        privateRadioButton.setText("private");
        buttonGroup1.add(privateRadioButton);
        jPanel3.add(privateRadioButton);

        protectedRadioButton.setText("protected");
        buttonGroup1.add(protectedRadioButton);
        jPanel3.add(protectedRadioButton);

        packageRadioButton.setText("package");
        buttonGroup1.add(packageRadioButton);
        jPanel3.add(packageRadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder("Modifiers"), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 20, 1, 20))));
        staticCB.setText("static");
        jPanel4.add(staticCB);

        finalCB.setText("final");
        jPanel4.add(finalCB);

        nativeCB.setText("native");
        jPanel4.add(nativeCB);

        volatileCB.setText("volatile");
        jPanel4.add(volatileCB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder(""));
        jLabel1.setText("Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        jPanel5.add(nameField, gridBagConstraints);

        jLabel2.setText("Type: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        jPanel5.add(typeField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = -1.0;
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBorder(new javax.swing.border.TitledBorder("Throws"));
        jLabel61.setText("Exception: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = -1.0;
        jPanel6.add(jLabel61, gridBagConstraints);

        jTextField61.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.weightx = 0.8;
        jPanel6.add(jTextField61, gridBagConstraints);

        jList11.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel6.add(jList11, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jButton31.setText("Add");
        jButton31.setToolTipText("");
        jPanel8.add(jButton31);

        jButton4.setText("Delete");
        jPanel8.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        jPanel6.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.8;
        jPanel2.add(jPanel6, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBorder(new javax.swing.border.TitledBorder("Argoments"));
        jLabel6.setText("Name: ");
        jPanel7.add(jLabel6, new java.awt.GridBagConstraints());

        jTextField6.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jTextField6, gridBagConstraints);

        jLabel7.setText("Type: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel7.add(jLabel7, gridBagConstraints);

        jTextField7.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel7.add(jTextField7, gridBagConstraints);

        jList1.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel7.add(jList1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jButton3.setText("Add");
        jButton3.setToolTipText("");
        jPanel1.add(jButton3);

        jButton5.setText("Delete");
        jPanel1.add(jButton5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 3;
        jPanel7.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.8;
        jPanel2.add(jPanel7, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        method.setName(null);
        if (cancel_command != null)
            cancel_command.execute();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        method.setName( nameField.getText() );
        method.setType( typeField.getText() );
        
        if (publicRadioButton.isSelected())
            method.setVisibility("public");
        else if (privateRadioButton.isSelected())
            method.setVisibility("private");
        else if (protectedRadioButton.isSelected())
            method.setVisibility("protected");
        else if (packageRadioButton.isSelected())
            method.setVisibility("package");

        if (staticCB.isSelected()==true)
            method.addModifier("static");
        if (finalCB.isSelected()==true)
            method.addModifier("final");
        if (nativeCB.isSelected()==true)
            method.addModifier("native");
        if (volatileCB.isSelected()==true)
            method.addModifier("volatile");
        
        if (ok_command != null)
            ok_command.execute();
    }//GEN-LAST:event_OKButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox nativeCB;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jButton31;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField typeField;
    private javax.swing.JCheckBox volatileCB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton OKButton;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jButton5;
    private javax.swing.JRadioButton packageRadioButton;
    private javax.swing.JCheckBox finalCB;
    private javax.swing.JRadioButton publicRadioButton;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton CancelButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox staticCB;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton privateRadioButton;
    private javax.swing.JList jList11;
    private javax.swing.JRadioButton protectedRadioButton;
    // End of variables declaration//GEN-END:variables
    
}
