/*
 * name_panel.java
 *
 * Created on 2 novembre 2002, 15.43
 */

package org.af1_0.gui.panel;

import org.af1_0.gui.command.command;
/**
 *
 * @author  Luca
 */
public class edit_name_panel extends javax.swing.JPanel {
    String name;
    command ok_command = null;
    command cancel_command = null;
    
    /** Creates new form name_panel */
    public edit_name_panel() {
        initComponents();
        setSuggested("insert_name");
    }
    
    public void setSuggested(String name) {
        jTextField1.setText(name);
        jTextField1.setSelectionStart(0);
        jTextField1.setSelectionEnd(name.length());
    }
    
    public void setOkCommand(command ok) {
        ok_command = ok;
    }
    
    public void setCancelCommand(command cancel) {
        cancel_command = cancel;
    }
    
    /**
     * @return  */    
    public String getName() {
        return name;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();
        CANCELButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        OKButton.setBackground(new java.awt.Color(204, 204, 204));
        OKButton.setForeground(new java.awt.Color(0, 0, 0));
        OKButton.setText("Ok");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        jPanel1.add(OKButton);

        CANCELButton.setText("Cancel");
        CANCELButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELButtonActionPerformed(evt);
            }
        });

        jPanel1.add(CANCELButton);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.EmptyBorder(new java.awt.Insets(20, 20, 20, 20))));
        jLabel1.setText("Name: ");
        jPanel2.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(200, 20));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jPanel2.add(jTextField1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // Add your handling code here:
        if (evt.getKeyChar() == 13 || evt.getKeyChar() == 10) {
            name = jTextField1.getText();
            // execute OK
            if (ok_command != null)
                ok_command.execute();
        } else if (evt.getKeyChar() == 27) {
            // execute CANCEL
            name = null;
            if (cancel_command != null)
                cancel_command.execute();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void CANCELButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELButtonActionPerformed
        name = null;
        if (cancel_command != null)
            cancel_command.execute();
    }//GEN-LAST:event_CANCELButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        name = jTextField1.getText();
        if (ok_command != null)
            ok_command.execute();
    }//GEN-LAST:event_OKButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton CANCELButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
