/*
 * WizardDialogCOM.java
 *
 * Created on 28 dicembre 2002, 14.30
 */

package org.af1_0.plugin;

import org.af1_0.gui.wizard.*;

/**
 *
 * @author  Luca
 */
public class WizardDialogCOM extends javax.swing.JDialog {
    protected wizard_control wizard = new wizard_control();
    protected boolean pattern_applied = false;
    
    /** Creates new form WizardDialogCOM */
    public WizardDialogCOM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public wizard_control getWizardPanel() {
        return wizard;
    }
    
    public boolean patternHasApplied() {
        return pattern_applied;
    }
    
    public void terminate(boolean finish) {
        pattern_applied = finish;
        setVisible(false);
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = wizard;

        getContentPane().setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Component Pattern Wizard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 400));
        getContentPane().add(jPanel1, "wizard");

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new WizardDialogCOM(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
