/*
 * agent_selection.java
 *
 * Created on 2 dicembre 2002, 18.51
 */

package org.af1_0.gui.wizard;

import java.util.*;

/**
 *
 * @author  Luca
 */
public class agent_selection extends javax.swing.JPanel {
    
    /** Creates new form agent_selection */
    public agent_selection() {
        initComponents();
    }
    
    public void setAgentList(Vector agent_list) {
        AgentList.setSelectedIndex(-1);
        AgentList.setListData(agent_list);
    }
    
    public void setTitle(String titolo) {
        jLabel1.setText(titolo);
    }
    
    public String getAgentName() {
        if (AgentList.getSelectedIndex() == -1)
            return null;
        
        return AgentList.getSelectedValue().toString();
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel3 = new javax.swing.JPanel();
        AgentList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Select an agent from model"));
        AgentList.setBorder(new javax.swing.border.EtchedBorder());
        jPanel3.add(AgentList, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titolo");
        add(jLabel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AgentList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
