/*
 * pattern_list.java
 *
 * Created on 30 novembre 2002, 13.44
 */

package org.af1_0.gui.wizard;

import java.util.Vector;
import java.util.Iterator;
import javax.swing.ImageIcon;
//import ptk_resource.ImageRecoverer;
import java.net.URL;

import org.af1_0.pattern.pattern_description;
import org.af1_0.repository.repository_designer;
/**
 *
 * @author  Luca
 */
public class pattern_list extends javax.swing.JPanel {
    private Vector patterns = null;
    private pattern_description pattern_selected = null;
	private repository_designer repository;
	private ImageIcon structures[];
	private ImageIcon collaborations[];
    
    /** Creates new form pattern_list */
    public pattern_list() {
        initComponents();
    }
    
    public pattern_description getPatternSelected() {
        return pattern_selected;
    }
    
    public void setPatternList(Vector pattern_list) {
        patterns = pattern_list;
        this.repository = repository;
		
		structures = new ImageIcon[pattern_list.size()];
		collaborations = new ImageIcon[pattern_list.size()];
		
        Vector names = new Vector();
        Iterator it = pattern_list.iterator();
        while (it.hasNext()) {
            pattern_description patt = (pattern_description) it.next();
            names.add(patt.getName());
        }
        
        PatternList.setSelectedIndex(-1);
        PatternList.setListData(names);
        pattern_selected = null;
		structure.setIcon(null);
		collaboration.setIcon(null);
    }
    
    public void setTitle(String titolo) {
        jLabel1.setText(titolo);
    }
    
	private void getStructureImageIcon(int index,URL icon_url) {
		//ImageIcon icon = null;		
		if (structures[index] != null)
			return;
		
		if (icon_url!=null) {
			//System.out.println(icon_url.toString());
			structures[index] = new ImageIcon(icon_url);
		}
		//return icon;//image_recoverer.getIcon();		
	}
	private void getCollabImageIcon(int index,URL icon_url) {
		if (collaborations[index] != null)
			return;
		
		if (icon_url!=null) {
			//System.out.println(icon_url.toString());
			collaborations[index] = new ImageIcon(icon_url);
		}
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        PatternList = new javax.swing.JList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatternFieldList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        FieldTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        structure_panel = new javax.swing.JPanel();
        structure = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        collaboration_panel = new javax.swing.JPanel();
        collaboration = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titolo");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(200);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Select a pattern"));
        PatternList.setBorder(new javax.swing.border.EtchedBorder());
        PatternList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PatternListValueChanged(evt);
            }
        });

        jPanel3.add(PatternList, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(22, 100));
        PatternFieldList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Classification", "Intent", "Motivation", "Pre-conditions", "Post-conditions", "Participants", "Implementation availability", "Related Patterns" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        PatternFieldList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PatternFieldListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(PatternFieldList);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.NORTH);

        FieldTextArea.setEditable(false);
        FieldTextArea.setLineWrap(true);
        FieldTextArea.setTabSize(4);
        FieldTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(FieldTextArea);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Description", jPanel1);

        structure_panel.setLayout(new java.awt.BorderLayout());

        structure_panel.setToolTipText("null");
        structure.setBackground(new java.awt.Color(255, 255, 255));
        structure_panel.add(structure, java.awt.BorderLayout.CENTER);

        jScrollPane5.setViewportView(structure_panel);

        jTabbedPane1.addTab("Structure", jScrollPane5);

        collaboration_panel.setLayout(new java.awt.BorderLayout());

        collaboration.setBackground(new java.awt.Color(255, 255, 255));
        collaboration_panel.add(collaboration, java.awt.BorderLayout.CENTER);

        jScrollPane3.setViewportView(collaboration_panel);

        jTabbedPane1.addTab("Collaboration", jScrollPane3);

        jSplitPane1.setRightComponent(jTabbedPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

	private void PatternFieldListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PatternFieldListValueChanged
        int index = PatternFieldList.getSelectedIndex();
		switch (index) {
			case 0:
			FieldTextArea.setText(pattern_selected.getClassification());
			break;
			case 1:
			FieldTextArea.setText(pattern_selected.getIntent());
			break;
			case 2:
			FieldTextArea.setText(pattern_selected.getMotivation());
			break;
			case 3:
			FieldTextArea.setText(pattern_selected.getPreCondition());
			break;
			case 4:
			FieldTextArea.setText(pattern_selected.getPostCondition());
			break;
			case 5:
			FieldTextArea.setText(pattern_selected.getParticipants());
			break;
			case 6:
			FieldTextArea.setText(pattern_selected.getAvailability());
			break;
			case 7:
			FieldTextArea.setText(pattern_selected.getRelatedPatterns());
			break;
		}	
	}//GEN-LAST:event_PatternFieldListValueChanged

    private void PatternListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PatternListValueChanged
        int index = PatternList.getSelectedIndex();
        if (index != -1) {
            pattern_selected = (pattern_description) patterns.get(index);
            PatternFieldList.setSelectedIndex(0);
			PatternFieldList.ensureIndexIsVisible(0);
			FieldTextArea.setText(pattern_selected.getClassification());
			
			getStructureImageIcon(index,pattern_selected.getStructure());
			getCollabImageIcon(index,pattern_selected.getCollaboration());
			
//			ImageIcon structure_image = 
			structure.setIcon(structures[index]);
//			ImageIcon collab_image = 
			collaboration.setIcon(collaborations[index]);
        }
    }//GEN-LAST:event_PatternListValueChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel collaboration_panel;
    private javax.swing.JList PatternFieldList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel structure_panel;
    private javax.swing.JButton structure;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea FieldTextArea;
    private javax.swing.JButton collaboration;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList PatternList;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
