/*
 * pattern_list.java
 *
 * Created on 30 novembre 2002, 13.44
 */

package org.af1_0.gui.wizard;

import java.util.Vector;

/**
 *
 * @author  Luca
 */
public class target_selection extends javax.swing.JPanel {
    /** Creates new form pattern_list */
    public target_selection() {
        initComponents();
    }
    
    public void setAgentName(String a_name) {
        jTextField1.setText( a_name );
    }
    
    public String getEntityName() {
        if (selectRB.isSelected()) {
            if (EntityList.getSelectedValue() != null) 
                return EntityList.getSelectedValue().toString();
            else
                return null;
        }
        
        if (jTextField1.getText().equals(""))
            return null;
        
        return jTextField1.getText();
    }
    
    public void setEntityList(Vector entity_list) {
        EntityList.setSelectedIndex(-1);
        EntityList.setListData(entity_list);
    }
    
    public void setTitle(String titolo) {
        jLabel1.setText(titolo);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        editRB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        selectRB = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        EntityList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titolo");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        editRB.setText("Edit new name");
        buttonGroup1.add(editRB);
        jPanel2.add(editRB);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 20, 1, 20)));
        jTextField1.setText("jTextField1");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        selectRB.setText("Select name from model");
        buttonGroup1.add(selectRB);
        jPanel2.add(selectRB);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 20, 1, 20)));
        EntityList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EntityListFocusGained(evt);
            }
        });

        jPanel3.add(EntityList, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void EntityListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EntityListFocusGained
        selectRB.setSelected(true);
    }//GEN-LAST:event_EntityListFocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        editRB.setSelected(true);
    }//GEN-LAST:event_jTextField1FocusGained
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton selectRB;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JList EntityList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton editRB;
    // End of variables declaration//GEN-END:variables
    
}
