/*
 * wizard_control.java
 *
 * Created on 30 novembre 2002, 11.25
 */

package org.af1_0.gui.wizard;

import org.af1_0.gui.command.command;

/**
 *
 * @author  Luca
 */
public class wizard_control extends javax.swing.JPanel {
    protected pattern_list pattern_panel = new pattern_list();
    protected pattern_overview overview_panel = new pattern_overview();
    protected target_selection selection_panel = new target_selection();
    protected agent_selection agent_panel = new agent_selection();
    protected role_selection role_panel = new role_selection();

    protected command cancel = null;
    protected command previous = null;
    protected command next = null;
    protected command ok = null;
    
    /** Creates new form wizard_control */
    public wizard_control() {
        initComponents();
    }
    
    public pattern_list getPatternListPanel() {
        return pattern_panel;
    }

    public pattern_overview getPatternOverviewPanel() {
        return overview_panel;
    }

    public target_selection getSelectionPanel() {
        return selection_panel;
    }

    public agent_selection getAgentTargetPanel() {
        return agent_panel;
    }

    public role_selection getRoleTargetPanel() {
        return role_panel;
    }

    public void setCancel(command a_command) {
        cancel = a_command;
        if (a_command == null)
            Cancel.setEnabled(false);
        else
            Cancel.setEnabled(true);
    }
    
    public void setPrevious(command a_command) {
        previous = a_command;
        if (a_command == null)
            Previous.setEnabled(false);
        else
            Previous.setEnabled(true);
    }

    public void setNext(command a_command) {
        next = a_command;
        if (a_command == null)
            Next.setEnabled(false);
        else
            Next.setEnabled(true);
    }
    
    public void setOk(command a_command) {
        ok = a_command;
        if (a_command == null)
            Ok.setEnabled(false);
        else
            Ok.setEnabled(true);
    }
    
    public void showCard(String card_name) {
        ((java.awt.CardLayout) jPanel3.getLayout()).show(jPanel3,card_name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        component_list = pattern_panel;
        overview = overview_panel;
        target_selection = selection_panel;
        agent_select = agent_panel;
        role_select = role_panel;

        setLayout(new java.awt.BorderLayout());

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel1.add(Cancel);

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        jPanel1.add(Previous);

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        jPanel1.add(Next);

        Ok.setText("Apply");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        jPanel1.add(Ok);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel3.add(component_list, "component_list");

        jPanel3.add(overview, "overview");

        jPanel3.add(target_selection, "target");

        jPanel3.add(agent_select, "agent");

        jPanel3.add(role_select, "role");

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        if (ok != null)
            ok.execute();
    }//GEN-LAST:event_OkActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if (next != null)
            next.execute();
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        if (previous != null)
            previous.execute();
    }//GEN-LAST:event_PreviousActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        if (cancel != null)
            cancel.execute();
    }//GEN-LAST:event_CancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel overview;
    private javax.swing.JPanel agent_select;
    private javax.swing.JPanel component_list;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel role_select;
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel target_selection;
    // End of variables declaration//GEN-END:variables
    
}
