/*
 * option_controls.java
 *
 * Created on 7 dicembre 2002, 9.21
 */

package org.af1_0.gui.options;

import org.af1_0.gui.command.command;

/**
 *
 * @author  Luca
 */
public class option_controls extends javax.swing.JPanel {
    protected repository_option repository_panel = new repository_option();
    protected project_panel project_sheet = new project_panel();
    
    protected command cancel = null;
    protected command ok = null;
    
    /** Creates new form option_controls */
    public option_controls() {
        initComponents();
    }
    
    public repository_option getRepositoryPanel() {
        return repository_panel;
    }
    
    public project_panel getProjectPanel() {
        return project_sheet;
    }

    public void setTitle(String titolo) {
        jLabel1.setText("Options panel: "+titolo);
    }

    public void setCancel(command a_command) {
        cancel = a_command;
        if (a_command == null)
            Cancel.setEnabled(false);
        else
            Cancel.setEnabled(true);
    }

    public void setOk(command a_command) {
        ok = a_command;
        if (a_command == null)
            Ok.setEnabled(false);
        else
            Ok.setEnabled(true);
    }
    
    public void showCard(String card_name) {
        ((java.awt.CardLayout) jPanel3.getLayout()).show(jPanel3,card_name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        repository_card = repository_panel;
        mas_options = project_sheet;

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Option panel");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel1.add(Cancel);

        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        jPanel1.add(Ok);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel3.add(repository_card, "repository");

        jPanel3.add(mas_options, "project");

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        if (cancel != null)
            cancel.execute();
    }//GEN-LAST:event_CancelActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        if (ok != null)
            ok.execute();
    }//GEN-LAST:event_OkActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel repository_card;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mas_options;
    // End of variables declaration//GEN-END:variables
    
}
