/*
 * project_panel.java
 *
 * Created on 10 dicembre 2002, 16.06
 */

package org.af1_0.gui.options;

/**
 *
 * @author  Luca
 */
public class project_panel extends javax.swing.JPanel {
    
    /** Creates new form project_panel */
    public project_panel() {
        initComponents();
    }
    
    public void suggestPlatform(int pl) {
        if (pl == 0) {
            JadeButton.setSelected(true);
            FIPAOSButton.setSelected(false);
        } else {
            JadeButton.setSelected(false);
            FIPAOSButton.setSelected(true);
        }
    }
    
    public String getPlatform() {
        if (JadeButton.isSelected())
            return "Jade";

        return "FIPAOS";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JadeButton = new javax.swing.JRadioButton();
        FIPAOSButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Agetn Platform Selection"));
        JadeButton.setText("Jade platform");
        buttonGroup1.add(JadeButton);
        jPanel1.add(JadeButton);

        FIPAOSButton.setText("FIPAOS platform");
        buttonGroup1.add(FIPAOSButton);
        jPanel1.add(FIPAOSButton);

        add(jPanel1);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FIPAOSButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton JadeButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
