/*
 * repository_option.java
 *
 * Created on 7 dicembre 2002, 10.35
 */

package org.af1_0.gui.options;

import org.af1_0.repository.*;

/**
 *
 * @author  Luca
 */
public class repository_option extends javax.swing.JPanel {
    protected repository_proxy user_defined_repository = null;
    
    /** Creates new form repository_option */
    public repository_option() {
        initComponents();
    }
    
    public void setCurrentRepository(int num) {
        if (num==0) {
            locale.setSelected(true);
            mozart.setSelected(false);
            user_defined.setSelected(false);
        } else if (num==1) {
            locale.setSelected(false);
            mozart.setSelected(true);
            user_defined.setSelected(false);
        } else {
            locale.setSelected(false);
            mozart.setSelected(false);
            user_defined.setSelected(true);
        }
    }
    
    public void setUserUrl(String user_url) {
        jTextField1.setText(user_url);
    }
    
    public repository_designer getRepository() {
        repository_designer rep = null;
        if ( locale.isSelected() ) 
            rep = new repository_locale();
        else if ( mozart.isSelected() )
            rep = new repository_proxy("mozart.csai.unipa.it");
        else
            rep = user_defined_repository;
        
        return rep;         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        locale = new javax.swing.JRadioButton();
        mozart = new javax.swing.JRadioButton();
        user_defined = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ConnectButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        locale.setText("Connect to locale repository");
        buttonGroup1.add(locale);
        jPanel1.add(locale);

        mozart.setText("Connect to standard AgentFactory repository");
        buttonGroup1.add(mozart);
        jPanel1.add(mozart);

        user_defined.setText("Connect to user defined repository");
        buttonGroup1.add(user_defined);
        jPanel1.add(user_defined);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 20, 1, 20)));
        jPanel3.add(jTextField1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setBorder(new javax.swing.border.TitledBorder("User defined repository connection test"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Press button to test the connection to remote server");
        jPanel4.add(jLabel1);

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });

        jPanel5.add(ConnectButton);

        jPanel4.add(jPanel5);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("current state = not response");
        jPanel4.add(jLabel2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    // prova a connettersi al database
    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
        user_defined_repository = new repository_proxy(jTextField1.getText());
        if ( user_defined_repository.test() == false) {
            user_defined_repository = null;
            jLabel2.setText("current state = not response");
        } else {
            jLabel2.setText("current state = connected");
        }
    }//GEN-LAST:event_ConnectButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton user_defined;
    private javax.swing.JRadioButton locale;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton mozart;
    private javax.swing.JButton ConnectButton;
    private javax.swing.JPanel jPanel5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
