/*
 * codeView.java
 *
 * Created on 25 novembre 2002, 10.19
 */

package org.af1_0.gui;

import java.util.List;

import org.af1_0.mas.multi_agent_system;
import org.af1_0.entity.java_class;
import org.af1_0.gui.xml.*;
/**
 *
 * @author  Luca
 */
public class codeView extends javax.swing.JPanel {
    protected java_class agent = null;
    protected List relation_list = null;
    //protected String code;
    
    /** Creates new form codeView */
    public codeView() {
        initComponents();
    }
    
    public void clear() {
        codeArea.setText("");
    }        
    
    public void setRelations(List list) {
        relation_list = list;
    }
    
    public void setAgent(java_class agent_to_show,multi_agent_system model) {
        agent_to_java transform = new agent_to_java(agent_to_show,model);
        
        String code = transform.getJava();
        codeArea.setText(code);
    }

   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        codeArea.setTabSize(4);
        codeArea.setDragEnabled(true);
        jScrollPane1.setViewportView(codeArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea codeArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
